// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Glimpse.Site.Areas.Version.Controllers
{
    public partial class CheckController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CheckController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected CheckController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Release()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Release);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public CheckController Actions { get { return MVC.Version.Check; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Version";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Check";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Check";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Release = "Release";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Release = "Release";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string details = "details";
            public readonly string withDetails = "withDetails";
        }
        static readonly ActionParamsClass_Release s_params_Release = new ActionParamsClass_Release();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Release ReleaseParams { get { return s_params_Release; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Release
        {
            public readonly string package = "package";
            public readonly string version = "version";
            public readonly string stamp = "stamp";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string Release = "Release";
            }
            public readonly string Index = "~/Areas/Version/Views/Check/Index.cshtml";
            public readonly string Release = "~/Areas/Version/Views/Check/Release.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_CheckController : Glimpse.Site.Areas.Version.Controllers.CheckController
    {
        public T4MVC_CheckController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Glimpse.Package.VersionCheckDetails details, bool withDetails);

        public override System.Web.Mvc.ActionResult Index(Glimpse.Package.VersionCheckDetails details, bool withDetails)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "details", details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "withDetails", withDetails);
            IndexOverride(callInfo, details, withDetails);
            return callInfo;
        }

        partial void ReleaseOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string package, string version, string stamp);

        public override System.Web.Mvc.ActionResult Release(string package, string version, string stamp)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Release);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "package", package);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "version", version);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "stamp", stamp);
            ReleaseOverride(callInfo, package, version, stamp);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
